[package]
name = "module"
version = "0.0.0"
edition = "2024"
description = '''
Modular NixOS-style configuration library.
'''
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

[features]
std = []
serde = ["dep:serde"]

[lints]
workspace = true
