[package]
name = "module"
version.workspace = true
authors = ["threadexio"]
edition.workspace = true
rust-version.workspace = true
description = '''
Modular NixOS-style configuration crate.
'''
documentation = "https://docs.rs/module"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "module_nightly"]
rustdoc-args = ["--cfg", "module_nightly"]

[dependencies]
module-derive = { version = "0.3.1", path = "../module-derive", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = { version = "1" }

[features]
std = []
derive = ["dep:module-derive"]
serde = ["dep:serde"]

default = ["std"]

[lints]
workspace = true
