[package]
name = "module-derive"
version.workspace = true
authors = ["threadexio"]
edition.workspace = true
rust-version.workspace = true
description = '''
Derive macros for the `module` crate.
'''
documentation = "https://docs.rs/module-derive"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1" }
syn = { version = "2" }
quote = { version = "1" }

[lints]
workspace = true
