[package]
name = "module-util"
version.workspace = true
authors = ["threadexio"]
edition.workspace = true
rust-version.workspace = true
description = '''
Utilities for working with module.
'''
documentation = "https://docs.rs/module-util"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
autotests = false

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "module_nightly"]
rustdoc-args = ["--cfg", "module_nightly"]

[dependencies]
module = { version = "0.4.0", default-features = false, path = "../module" }
serde = { version = "1", default-features = false, optional = true }
serde_json = { version = "1", optional = true }
toml = { version = "1", optional = true }

[dev-dependencies]
module = { version = "0.4.0", features = ["derive"], path = "../module" }

[features]
std = []
serde = ["dep:serde"]
file = ["std", "serde", "serde/std", "serde/derive"]
json = ["file", "dep:serde_json"]
toml = ["file", "dep:toml"]

default = ["std"]

[[test]]
name = "test_file"
path = "tests/test_file.rs"
required-features = ["json", "module/serde"]

[[test]]
name = "test_file_format_toml"
path = "tests/test_file_format_toml.rs"
required-features = ["toml", "module/serde"]

[lints]
workspace = true
