name: CI

on:
  push:
    paths:
      - .github/workflows/**
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - module/**
      - module-derive/**
      - examples/**
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check --all
      - run: cargo clippy --workspace --all-features

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features --no-run
      - run: cargo test --workspace --all-features -- --nocapture --quiet

  doc:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - run: cargo +nightly doc --workspace --no-deps --all-features

  miri:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@miri
      - run: cargo +nightly miri setup
      - run: cargo +nightly miri test --workspace --all-features --lib
